### ISSUE TITLE
Loop conditions

### ISSUE THREAD

**Issue by Clerish** [archie-m-vist/rigdio#15]
Please add conditions to allow:
- Having a horn not loop when it ends, until the player's button gets clicked again.
- Having the horn start from the beginning every time it's played.
- Having the horn start from the beginning every X times it's played.

**Comment by archie-m-vist** [comment]
Horn starting from the beginning every time it was played was added in f146d690ebc7c1481a0f69e4a6a2da367be3cb83.

**Comment by archie-m-vist** [comment]
24f0b424dd075ab63cedc223ee95ad7d5689ebc5 added every Nth time (`pause restart every n`).

9b66ce67e10f44edaf466b8b1d6e80a0dab920ac added `end stop` which disables looping.
